export const users = [
  {
    id: 1,
    name: 'Pintu',
    username: 'pintu',
    isBlocked: false,
    role: 'admin',
    permissions: ['read', 'write', 'delete', 'update'],
  },
  {
    id: 2,
    name: 'Rohit Sharma',
    username: 'rohit',
    isBlocked: false,
    role: 'manager',
    permissions: ['read', 'write', 'update'],
  },
  {
    id: 3,
    name: 'Sana Khan',
    username: 'sana',
    isBlocked: true,
    role: 'editor',
    permissions: ['read', 'write'],
  },
  {
    id: 4,
    name: 'Ankit Verma',
    username: 'ankit',
    isBlocked: false,
    role: 'viewer',
    permissions: ['read'],
  },
  {
    id: 5,
    name: 'Neha Gupta',
    username: 'neha',
    isBlocked: true,
    role: 'admin',
    permissions: ['read', 'write', 'delete'],
  },
  {
    id: 6,
    name: 'Amit Sinha',
    username: 'amit',
    isBlocked: false,
    role: 'support',
    permissions: ['read', 'update'],
  },
  {
    id: 7,
    name: 'Divya Mehra',
    username: 'divya',
    isBlocked: false,
    role: 'moderator',
    permissions: ['read', 'write', 'update'],
  },
  {
    id: 8,
    name: 'Kunal Raj',
    username: 'kunal',
    isBlocked: false,
    role: 'analyst',
    permissions: ['read'],
  },
];
